apiVersion: v1
kind: Service
metadata:
  labels:
    name: tile38-follower
  namespace: tile38
  name: tile38-follower
spec:
  type: ClusterIP
  ports:
    - name: tile38 
      port: 9851
  selector:
    name: tile38-follower